- include_tasks: mirror-user.yml

- import_role:
    name: httpd
  vars:
    httpd_tls: True
    httpd_html_autoindex_title: "CentOS Vault Mirror"
    httpd_html_autoindex_content: "{{ vault_httpd_header }}" 

- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ vault_httpd_hostname }}"
  tags:
    - tls

- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ vault_httpd_origin_hostname }}"
  tags:
    - tls
  when: vault_httpd_origin_node  

- name: Adding vhost file
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - 40_vault.conf
    - ssl-vault.conf
  notify:
    - reload_httpd
  tags:
    - httpd 

- name: Ensuring some selinux booleans are enabled
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  with_items:
    - httpd_enable_homedirs
    - httpd_read_user_content

- name: Script to gather mirror content
  template:
    src: rsync-master-centos-vault.j2
    dest: "/home/{{ vault_local_user }}-scripts/rsync-master-centos-vault"
    mode: 0755

- name: Cron job to rsync content from upstream node
  cron:
    name: "CentOS Vault mirror rsync job"
    job: "/home/{{ vault_local_user }}-scripts/rsync-master-centos-vault {{ vault_rsync_from }} > /dev/null 2>&1"
    minute: "*/12"
    user: "{{ vault_local_user }}"

- include_tasks: rsyncd.yml
  when: vault_rsyncd

- include_tasks: monitoring.yml  
