- import_role:
    name: rsyncd

- name: Dropping the rsyncd snippet for mirror
  template:
    src: 09_full-store.conf.j2
    dest: /etc/rsyncd.d/09_full-store.conf
    mode: 0644
  notify:
    - rebuild_rsyncd

- name: Needed selinux booleans for rsyncd
  seboolean:
    name: rsync_export_all_ro
    persistent: yes
    state: yes

- name: Distributing custom selinux policies
  copy: 
    src: "selinux/{{ ansible_distribution_version[0] }}/{{ item }}" 
    dest: "/etc/selinux/centos/{{ item }}"
  register: sepolicy
  with_items:
    - centos-msync-rsyncd.pp

- name: reload custom selinux files
  shell: /usr/sbin/semodule -u "/etc/selinux/centos/centos-msync-rsyncd.pp"
  when: ansible_selinux.status == "enabled" and sepolicy.changed

